### ISSUE TITLE
lightbox package fails to build with `yarn install`

### ISSUE THREAD

**Issue by nagarajanchinnasamy** [mdarche/maker-ui#27]
After unzipping the source, building with `yarn install` fails with following error:

> lerna ERR! yarn run prepare exited 1 in '@maker-ui/lightbox'
> lerna ERR! yarn run prepare stdout:
> yarn run v1.22.4
> $ microbundle --no-compress --jsx React.createElement
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> lerna ERR! yarn run prepare stderr:
> node-resolve: setting options.module is deprecated, please override options.mainFields instead
> node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
> node-resolve: setting options.module is deprecated, please override options.mainFields instead
> node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
> node-resolve: setting options.module is deprecated, please override options.mainFields instead
> node-resolve: setting options.jsnext is deprecated, please override options.mainFields instead
> Error: 'default' is not exported by src\play.svg
> 
> at xxxxxxxxxx\maker-ui\packages\lightbox\src\Preview.js:4:7
> 
> 2: import { Box } from 'theme-ui'
> 3:
> 4: import playIcon from './play.svg'
>           ^
> 5:
> 6: const Preview = ({ index, set, urls, show }) => {
> 
> error Command failed with exit code 1.
> 
> lerna ERR! yarn run prepare exited 1 in '@maker-ui/lightbox'

**Comment by mdarche** [comment]
Hey! Thank you very much for your interest in the project.

I'm currently rebuilding everything in Typescript and implementing my own `Box` component that should resolve this bug and a few others in @maker-ui/components (see the typescript branch for progress updates). 

Closing this for now as the API will be a little different in the next 2 weeks.
